### PR TITLE
Update to latest dependencies, add responsive-tag

### PR DESCRIPTION
**Pull request by lessp**

### CODE REVIEW

**Comment by MargaretKrutikova** [comment]
Hej! Thanks a lot for the contribution!
I have just one question, are we sure that `reason-apollo-hooks` works seamlessly with `bs-platform` v7.3.2? Maybe I am wrong, but I thought I had some compatibility problems with this version, but not v7.0.1. I can check tonight after work, otherwise looks great 🙂

**Comment by lessp** [comment]
> Hej! Thanks a lot for the contribution!
> I have just one question, are we sure that `reason-apollo-hooks` works seamlessly with `bs-platform` v7.3.2? Maybe I am wrong, but I thought I had some compatibility problems with this version, but not v7.0.1. I can check tonight after work, otherwise looks great 🙂

Possibly not! I've not added any GraphQL to our project yet so can't say, but it might indeed be the right move to hold back updating `bs-platform` if that's the case to not give newcomers a hard time! 🙂

**Comment by MargaretKrutikova** [comment]
Just tested everything with freshly installed `reason-apollo-hooks` and `@baransu/graphql_ppx_re`, works seamlessly! Thanks a lot for your contribution 🙂

**Comment by MargaretKrutikova** [comment]
The repo will finally get the right colour for `ReasonML` 😉

**Pull request merged**
